# Generated by Django 3.1.2 on 2020-10-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complete',
            old_name='text1',
            new_name='text',
        ),
    ]
